[package]
name = "storybook2"
version = "0.1.0"
edition = "2021"
publish = false

[[bin]]
name = "storybook"
path = "src/storybook2.rs"

[dependencies]
anyhow.workspace = true
# TODO: Remove after diagnosing stack overflow.
backtrace-on-stack-overflow = "0.3.0"
clap = { version = "4.4", features = ["derive", "string"] }
chrono = "0.4"
gpui = { package = "gpui2", path = "../gpui2" }
itertools = "0.11.0"
log.workspace = true
rust-embed.workspace = true
serde.workspace = true
settings2 = { path = "../settings2" }
simplelog = "0.9"
smallvec.workspace = true
strum = { version = "0.25.0", features = ["derive"] }
theme = { path = "../theme" }
theme2 = { path = "../theme2" }
ui = { package = "ui2", path = "../ui2", features = ["stories"] }
util = { path = "../util" }

[dev-dependencies]
gpui = { package = "gpui2", path = "../gpui2", features = ["test-support"] }
